services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: forum
    ports:
      - "5432:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8001:8000"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/forum"
    volumes:
      - ./back:/app

  frontend:
    image: nginx:latest
    container_name: frontend
    volumes:
      - ./front:/usr/share/nginx/html
      - ./front/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8000:80"
    depends_on:
      backend:
        condition: service_started
